import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/header';

const merriweather = Merriweather({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-merriweather',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${merriweather.variable} font-merriweather`}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
